"""added created_at columns

Revision ID: 591514ef8698
Revises: 25e4ceb8dc89
Create Date: 2019-07-04 20:59:29.032995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591514ef8698'
down_revision = '25e4ceb8dc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'confirmed')
    op.drop_column('clients', 'created_at')
    # ### end Alembic commands ###
