"""added deleted_on fields

Revision ID: 5cd2f2817f21
Revises: 6e7b5750387d
Create Date: 2019-07-09 20:54:15.191866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd2f2817f21'
down_revision = '6e7b5750387d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('deleted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'deleted_on')
    op.drop_column('client', 'deleted_on')
    op.drop_column('user', 'deleted_on')
    # ### end Alembic commands ###
