"""Rename tables and add index constraints

Revision ID: 6e7b5750387d
Revises: afc4f2e18c83
Create Date: 2019-07-08 14:39:05.262370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e7b5750387d'
down_revision = 'afc4f2e18c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.rename_table('clients', 'client')
    op.create_index(op.f('ix_client_created_at'), 'client', ['created_at'], unique=False)
    op.rename_table('projects', 'project')
    op.add_column('project', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_column('project', 'created_at')
    op.drop_index(op.f('ix_client_created_at'), table_name='client')
    op.rename_table('client', 'clients')
    op.rename_table('project', 'projects')
    # ### end Alembic commands ###
