"""added new deleted field

Revision ID: 71084cc3475d
Revises: 591514ef8698
Create Date: 2019-07-06 17:56:32.964912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71084cc3475d'
down_revision = '591514ef8698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    # ### end Alembic commands ###
