"""Changed table names

Revision ID: b52e2a4e0b37
Revises: c1e7cc1fd222
Create Date: 2019-05-09 17:25:28.418225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52e2a4e0b37'
down_revision = 'c1e7cc1fd222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('_password', sa.String(length=128), nullable=True))
    op.drop_column('Users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('Users', '_password')
    # ### end Alembic commands ###
